model:
  base_learning_rate: 4.5e-6
  target: ldm.models.brdf_unet_decoder_render.RGB2BRDF
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSONLY
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      image_size: 32
      in_channels: 4
      out_channels: 16
      model_channels: 320
      attention_resolutions:
      - 4
      - 2
      - 1
      num_res_blocks: 2
      channel_mult:
      - 1
      - 2
      - 4
      - 4
      num_heads: 8
      use_spatial_transformer: true
      transformer_depth: 1
      context_dim: 768
      use_checkpoint: true
      legacy: false

    vae_config:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: ldm.data.simple.ABODataModuleFromConfig
  params:
    root_dir: "/home/ubuntu/data/abo"
    batch_size: 2
    num_workers: 4
    total_view: 90
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256


lightning:
  find_unused_parameters: True
  metrics_over_trainsteps_checkpoint: True
  modelcheckpoint:
    params:
      every_n_train_steps: 1000
  callbacks:
    image_logger:
      target: main_vae.ImageLogger
      params:
        batch_frequency: 500
        max_images: 32
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 32
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    max_epochs: 3000
    check_val_every_n_epoch: 3
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
